### PR TITLE
Feat/affordance extension

### PR DESCRIPTION
**Pull request by jo-bru**
This PR extends the `xarm-commander` and `xarm-grpc-service` functionality.
The following methods are newly implemented:

Motion related methods:
- `SetPosition`: additional support for adapting speed, acceleration, arc transitions
- `SetServoAngle`
- `MoveCircle
- `SetPauseTime`: to add pause between movements
- `GetServoAngles`
- `LastUsed` values: `Position`, `TCPSpeed`, `TCPAcc`, `Angles`, `JointSpeed`, `JointAcc`

System actions:
- `Reset`: not yet tested (see #48)
- `EmergencyStop`: not yet tested (see #48)

General System Properties:
- `GetMode`
- `GetDefaultIsRadian`: `SetDefaultIsRadian` is deactivated since its usage may be dangerous without further safety measures (see #46 ).
- `GetRobotSN`: does not work yet (see #43 )
- `GetCmdnum`: not yet tested well (see #47)
- `Get/SetCollisionSensitivity`
- `Get/SetTeachSensitivity`

Safety settings:
- Reduced Mode: Joint range and collision rebound not yet supported
- Safety Boundary: `GetFence/SafetyMode` not yet supported

Other:
- Advanced properties: `Temperatures`, `Voltages`, `Currents`
- Kinematics: `GetInverseKinematics`, `GetForwardKinematics`
- Simulation: `Get/SetSimulationRobot` switch between simulation and real => all other commands can also be used for the simulated robot!
- Counter: `GetCounter`, `SetCounterReset`, `SetCounterIncrease`

There are still interesting methods that need to be implemented. However, I wanted to go on and implement first these methods in the Servient and then come back to further implement other methods.

Other interesting methods to implement are:
- Trajectory related methods
- Gripper related methods
- TCP settings
- Error/warn handing

### CODE REVIEW

**Comment by iomz** [comment]
Thanks, I'll have a look tomorrow afternoon.

**Review by iomz — APPROVED** [review]
This is astounding. Thanks a bunch, @jo-bru, great work!
I just have a trivial recommendation with #50 – please merge that to this PR if it makes sense to you. The same might as well apply to the `XAPIServiceImp` or rpc services, but I think the rpc service prototypes at least are just good as they are conveying the type of services...

**Comment by jo-bru** [comment]
Thank you! :) 
I might change the service order in the future (also in the `wot-fx` repo), but leave it for now as it is.

**Comment by iomz** [comment]
Ok! Thanks!

**Pull request merged**
